name: Timeless Wisdom Series
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5142
title: Timeless Wisdom Series
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e1f23'
    - '#bf8383'
    - '#3d464d'
    - '#ebe4dc'
    - '#9db79a'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
