name: TWS
favicon: null
layout_spectrum: 0.9586070282384753
typography_spectrum: 0.8730051827151328
title: Timeless Wisdom Series
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#901d3a'
    - '#111a17'
    - '#ffffff'
    - '#b06428'
    - '#d6ab80'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
